apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment
  labels:
    app: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: lerndevops/addressbook:latest 
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Service
metadata:
  name: sampleapp-service
spec:
  type: NodePort
  selector:
    app: sampleapp
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32105
    
    
apiVersion: v1
kind: ReplicationController
metadata:
  name: first-rc
spec:
  replicas: 6
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello1
        image: tomcat
        ports:
        - containerPort: 8080
